CREATE TABLE IF NOT EXISTS greetings (
    id BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT UNSIGNED NOT NULL,
    message TEXT NOT NULL,
    CONSTRAINT R_greetingsUserIdForeign FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);